### ISSUE TITLE
BUG - Not available after couple of days. 2nd time in two weeks

### ISSUE THREAD

**Issue by TheFrisianDude** [muppet3000/homeassistant-growatt_server_api#40] opened 2023-09-29 09:39 UTC
After a couple of days the power outage is stuck on a random value. It keeps displaying that value and does not change anymore. Other values are working from the growatt integration keep working.

It's the 2nd time in a couple of weeks where i just started with it. After first time i deleted the device and reconfigured the integration, working again after it.

Any tips to solve or troubleshoot this? Without keep reconfiguring this after x days?

**Comment by muppet3000** [comment] 2023-09-29 15:22
There's several extensive conversations on this going on in other places:
https://github.com/home-assistant/core/issues/100874

https://github.com/muppet3000/homeassistant-growatt_server_api/issues/15

I've even updated the main readme for this plugin see "IMPORTANT": https://github.com/muppet3000/homeassistant-growatt_server_api

I'm going to close this as a duplicate of the others.

**Closed by muppet3000** 2023-09-29 15:22 UTC
Labels: bug, triage
