### ISSUE TITLE
BUG - HA not pulling stats until 04:00 daily

### ISSUE THREAD

**Issue by jasongoff** [muppet3000/homeassistant-growatt_server_api#23] opened 2023-02-11 09:04 UTC
Hi Chris,

Since updating to 1.0.2 of the integration, HA is not getting stats until around 04:00, and then pulling in all consumption into that hourly period (see graph)
![image](https://user-images.githubusercontent.com/4741507/218249998-3641e3e7-f71c-40e2-aaad-e9aec7afb5e9.png)

I've also attached the logs from last night where it appears to start erroring around midnight.
[home-assistant_2023-02-11T09-07-47.993Z.log](https://github.com/muppet3000/homeassistant-growatt_server_api/files/10713025/home-assistant_2023-02-11T09-07-47.993Z.log)

**Growatt Device Type**

Device(s): Hybrid Inverter

**Home Assistant information**
 - Home Assistant version: Home Assistant 2023.2.3
 - Growatt Server API Integration version: 1.0.2

**Additional context**

N/A

**Comment by Saentist** [comment] 2023-02-11 09:12
This is 4 o'clock in the morning or 16:00 ?
Less then 23% of earth population use imperial metrics.

**Comment by muppet3000** [comment] 2023-02-11 09:13
This isn't a bug with the integration, this is the same problem as https://github.com/muppet3000/homeassistant-growatt_server_api/issues/15

Your account probably got blocked for a period of time or the server was unavailable for a while and then everything got pulled in when it was available again.

If you haven't been following that other bug I recommend reading my summaries in it [here](https://github.com/muppet3000/homeassistant-growatt_server_api/issues/15#issuecomment-1423787751) and [here](https://github.com/muppet3000/homeassistant-growatt_server_api/issues/15#issuecomment-1424810061)

Closing this as a duplicate of the other bug.

**Closed by muppet3000** 2023-02-11 09:13 UTC
Labels: bug, triage
