### ISSUE TITLE
BUG - Growatt Integration does Not Connect

### ISSUE THREAD

**Issue by Windows81User** [muppet3000/homeassistant-growatt_server_api#38] opened 2023-09-26 10:34 UTC
**Describe the bug**

Hello,
Since yesterday around 09.00 the Home Assistant integration does not connect to the Growatt server anymore.

The connection via the Growatt web portal and the app works.

Do any of you have the same problem?

**To Reproduce**

**Growatt Device Type**

Device(s): MOD-TL37000-XH

**Home Assistant information**
 - Home Assistant version: 2023.9.0
 - Growatt Server API Integration version: Same Version in Home Assistant Core

**Additional context**

Logger: homeassistant.components.sensor
Source: components/growatt_server/sensor.py:43
Integration: Sensor (documentation, issues)
First occurred: 09:07:52 (1 occurrences)
Last logged: 09:07:52

Error while setting up growatt_server platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 87, in async_setup_entry
    devices, plant_id = await hass.async_add_executor_job(get_device_list, api, config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 43, in get_device_list
    login_response = api.login(config[CONF_USERNAME], config[CONF_PASSWORD])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/growattServer/__init__.py", line 132, in login
    data = json.loads(response.content.decode('utf-8'))['back']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by coleburg** [comment] 2023-09-28 17:27
Ive been using Postman, hitting their API with the following https://server.growatt.com/newTwoLoginAPI.do?userName=MYEMAIL&password=MYPASSWORD and this always worked up until yesterday.  

I orginally used Fiddler to get my traffic and work out that API call but its expired. anyone else been able to connect yet?

**Comment by muppet3000** [comment] 2023-09-28 19:53
Hi, this is a duplicate of #15 I recommend taking a read of the README on the front page of the repo: https://github.com/muppet3000/homeassistant-growatt_server_api (see: !IMPORTANT NOTICE!).

I have also posted lots of information here: https://github.com/home-assistant/core/issues/100874#issuecomment-1739911377 a little while ago, so please can you take a look through that as well.

**Closed by muppet3000** 2023-09-28 19:53 UTC
