### ISSUE TITLE
Can't login to Growatt server after halt in communications between HA an growatt

### ISSUE THREAD

**Issue by corove** [muppet3000/homeassistant-growatt_server_api#39] opened 2023-09-29 07:19 UTC
**Describe the bug**
I have used this HACS integration for some time now. But yesterday 28. september the system stopped communicating with the Growatt server, and all sensors stated "unavailable". I checked in the "shinePhone" how the status was, and i am sometimes getting the message "Network Timeout" and a checkbox saying "Done". But if I wait a few minutes, I get in and can see the same values as the inverter lcd screen shows. On the web-page "https://server.growatt.com/panel.do" i can see the live data as it supposed to show. I have tried to restart system, and have pulled out a fault list from the integration. I have tried to reinstall the integration, but only get the error "Unknown error occurred" with any of the servers I choose. What can i do to get this to work again?

I got the following log details before trying to reinstall integration: 
2023-09-28 20:01:30.764 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up growatt_server_api platform for sensor
"Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/growatt_server_api/sensor.py", line 88, in async_setup_entry
    devices, plant_id = await hass.async_add_executor_job(get_device_list, api, config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/growatt_server_api/sensor.py", line 51, in get_device_list
    user_id = login_response["user"]["id"]
              ~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'user'"

**Not able to Reinstall**

**Growatt Device Type**
<!-- Please log in to https://server.growatt.com/ the provide a list of items found under the 'device type' drop down, a screen grab of that page is also fine -->
Device(s): ShineWiFi-X, Firmware Version：3.1.0.5

**Home Assistant information**
 - Home Assistant version: 2023.9.2
 - Growatt Server API Integration version: v1.0.2

**Additional context**
<!-- -->
N/A
![error message](https://github.com/muppet3000/homeassistant-growatt_server_api/assets/112816811/4ac44e9d-13dc-42cc-aeca-28613fe8af38)

**Comment by muppet3000** [comment] 2023-09-29 07:22
Hi, this is a duplicate of https://github.com/muppet3000/homeassistant-growatt_server_api/issues/15 I recommend taking a read of the README on the front page of the repo: https://github.com/muppet3000/homeassistant-growatt_server_api (see: !IMPORTANT NOTICE!).

I have also posted lots of information here: https://github.com/home-assistant/core/issues/100874#issuecomment-1739911377 a little while ago, so please can you take a look through that as well.

**Closed by muppet3000** 2023-09-29 07:22 UTC
Labels: bug, triage
