### ISSUE TITLE
BUG - Growatt MOD 5000 TL3-X 3-fase doesnt show invertor values

### ISSUE THREAD

**Issue by horstefan** [muppet3000/homeassistant-growatt_server_api#18] opened 2023-02-01 10:06 UTC
**Describe the bug**

The Integration shows correct totals and does seem to recognise the inverter however individual measurements are not captured.

**To Reproduce**

See screenshots. 

**Growatt Device Type**

Device(s): MAX/MID/MAC

**Home Assistant information**
 - Home Assistant version: 2023.2.0b7
 - Growatt Server API Integration version: V1.0.1 (HACS)

**Additional context**

Growatt Screenshot
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/23259607/216012420-8f93fe90-8747-4a89-94e0-0856fc9356fc.png">

Total sensors (working):
<img width="327" alt="image" src="https://user-images.githubusercontent.com/23259607/216012581-52f9c94a-bc29-44c7-83bd-1fa2ba467c8f.png">

Invertor sensors: 
<img width="295" alt="image" src="https://user-images.githubusercontent.com/23259607/216012733-7e19248e-2d65-49c7-964e-27578cc4b254.png">

**Comment by muppet3000** [comment] 2023-02-01 11:33
Hi @horstefan - Thanks for logging this, especially since you're the first person to log a bug using the template correctly!!!! Gold Star for you!

We do not yet have support for MAX/MID/MAC systems.
This is stated on the info page here: https://github.com/muppet3000/homeassistant-growatt_server_api/blob/dev/info.md
It is also outlined in this ticket: https://github.com/muppet3000/homeassistant-growatt_server_api/issues/11

I'm going to mark this as a duplicate of the other ticket and close it. I recommend following the status of the other ticket as I'm planning on adding that support very soon.

**Closed by muppet3000** 2023-02-01 11:33 UTC
Labels: bug, triage

**Comment by horstefan** [comment] 2023-02-01 11:35
Thanks @muppet3000 . if providing my credentials or testing help you in the development; please reach out!

**Comment by muppet3000** [comment] 2023-02-01 11:37
I already have some sets of credentials. However, if you're happy to share credentials so I have more to test with that would be great.
There's details [here](https://github.com/muppet3000/homeassistant-growatt_server_api/blob/dev/FAQ.md#how-do-i-share-my-credentials-with-you-for-testingadding-new-features-for-my-system-type) on how to share them in a more secure manner than just passing me your own credentials.
